// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqR-ATeUjvAlCt8k7kTYRSUg5K--9bzZw',
    appId: '1:908828655450:web:c7d42931f9e23deadb3d63',
    messagingSenderId: '908828655450',
    projectId: 'attentionminder-3f4d6',
    authDomain: 'attentionminder-3f4d6.firebaseapp.com',
    storageBucket: 'attentionminder-3f4d6.firebasestorage.app',
    measurementId: 'G-HT10ZVSGEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVbf7JzKio5Cn3KURCWVEVVngjxgKMEU',
    appId: '1:908828655450:android:8664641de11f043edb3d63',
    messagingSenderId: '908828655450',
    projectId: 'attentionminder-3f4d6',
    storageBucket: 'attentionminder-3f4d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUp3slg2rhTTfIMoDx4OvmJ9-CVu66GI',
    appId: '1:908828655450:ios:56d6581ee66c0298db3d63',
    messagingSenderId: '908828655450',
    projectId: 'attentionminder-3f4d6',
    storageBucket: 'attentionminder-3f4d6.firebasestorage.app',
    androidClientId: '908828655450-is6o6u9o7u17ejmbhb5tf7e6hl1eng63.apps.googleusercontent.com',
    iosClientId: '908828655450-45pfs3nv3439mquonumkmjf5lkrlp7gj.apps.googleusercontent.com',
    iosBundleId: 'attentionminder.trufoxai.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgUp3slg2rhTTfIMoDx4OvmJ9-CVu66GI',
    appId: '1:908828655450:ios:38a230667ce2ddc4db3d63',
    messagingSenderId: '908828655450',
    projectId: 'attentionminder-3f4d6',
    storageBucket: 'attentionminder-3f4d6.firebasestorage.app',
    androidClientId: '908828655450-is6o6u9o7u17ejmbhb5tf7e6hl1eng63.apps.googleusercontent.com',
    iosClientId: '908828655450-9tvggnnf49djfi9102e3ia5c3cpsdsc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adhdMinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqR-ATeUjvAlCt8k7kTYRSUg5K--9bzZw',
    appId: '1:908828655450:web:129398f3eb987ee5db3d63',
    messagingSenderId: '908828655450',
    projectId: 'attentionminder-3f4d6',
    authDomain: 'attentionminder-3f4d6.firebaseapp.com',
    storageBucket: 'attentionminder-3f4d6.firebasestorage.app',
    measurementId: 'G-B2R2W03L6R',
  );

}